"""Identity filter for key pair pattern matching.

This module provides identity-based filtering for Packer-related resources
using the SSH key pair pattern as per Requirement 1.2.

The filter identifies instances launched with KeyPairs matching the pattern
"packer_*" (Packer_KeyPair).
"""

from reaper.filters.base import ResourceFilter
from reaper.models import (
    PackerElasticIP,
    PackerInstance,
    PackerKeyPair,
    PackerSecurityGroup,
    PackerSnapshot,
    PackerVolume,
)


class IdentityFilter(ResourceFilter):
    """Filter resources based on Packer key pair pattern.

    This implements Requirement 1.2: identify instances launched with
    KeyPairs matching the pattern "packer_*".

    WARNING: Instances are detected by the name of the SSH key that is
    automatically generated by Packer (pattern: packer_*). Do NOT use
    this application if you use similar key naming patterns for non-Packer
    instances, as they may be incorrectly identified and terminated.
    """

    # Pattern for Packer-generated key pairs
    KEY_PAIR_PATTERN = "packer_"

    def __init__(self, key_pattern: str | None = None):
        """
        Initialize identity filter.

        Args:
            key_pattern: Prefix pattern for key pair names (defaults to "packer_")
        """
        self.key_pattern = key_pattern or self.KEY_PAIR_PATTERN

    def matches_key_pattern(self, key_name: str) -> bool:
        """
        Check if key name matches the Packer pattern.

        This implements Requirement 1.2: identify instances with key_name
        starting with "packer_".

        Args:
            key_name: The key pair name to check

        Returns:
            True if key_name starts with the pattern, False otherwise
        """
        if not key_name:
            return False
        return key_name.startswith(self.key_pattern)

    def filter_instances(self, instances: list[PackerInstance]) -> list[PackerInstance]:
        """
        Filter instances with Packer key pair pattern.

        Returns only instances where key_name starts with "packer_".
        """
        return [
            instance
            for instance in instances
            if instance.key_name and self.matches_key_pattern(instance.key_name)
        ]

    def filter_volumes(self, volumes: list[PackerVolume]) -> list[PackerVolume]:
        """Filter volumes - pass through (volumes are associated with instances)."""
        return volumes

    def filter_snapshots(self, snapshots: list[PackerSnapshot]) -> list[PackerSnapshot]:
        """Filter snapshots - pass through (snapshots are associated with volumes)."""
        return snapshots

    def filter_security_groups(
        self, security_groups: list[PackerSecurityGroup]
    ) -> list[PackerSecurityGroup]:
        """Filter security groups with Packer pattern.

        SAFETY: Only returns security groups with names matching "packer_*".
        This prevents accidental deletion of production security groups
        during orphan cleanup (Phase 2).
        """
        return [
            sg for sg in security_groups if self.matches_key_pattern(getattr(sg, "group_name", ""))
        ]

    def filter_key_pairs(self, key_pairs: list[PackerKeyPair]) -> list[PackerKeyPair]:
        """Filter key pairs with Packer pattern."""
        return [kp for kp in key_pairs if self.matches_key_pattern(kp.key_name)]

    def filter_elastic_ips(self, elastic_ips: list[PackerElasticIP]) -> list[PackerElasticIP]:
        """Filter elastic IPs - pass through (associated with instances)."""
        return elastic_ips
